apiVersion: v2
name: dnation-jsonnet-translator
type: application
version: 0.1.1
appVersion: 0.1.1
description: dNation Translator is a simple container for translating jsonnet content stored in k8s configmaps to **grafana dashboards** or **prometheus rules**.
keywords:
  - jsonnet
  - json
  - kubernetes
  - grafana
  - dashboard
  - prometheus
  - rule
home: https://dnation.cloud
maintainers:
  - name: dnation
    email: cloud@dnation.cloud
icon: https://cdn.ifne.eu/public/icons/dnation_jsonnet_translator.png
