target_namespace: "default"
jsonnet_dashboards_selector: "grafana_dashboard_jsonnet=1"
grafana_label: "grafana_label"
jsonnet_rules_selector: "prometheus_rule_jsonnet=1"
prometheus_label: "prometheus_label"
grafana_dashboards_cm_name: "grafana-dashboards-generated"
prometheus_rules_object_name: "prometheus-rules-generated"
log: "INFO"
log_format: "default"
