{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.fullname" . }}
rules:
- apiGroups: ["*"]
  resources: ["configmaps", "prometheusrules"]
  verbs: ["get", "watch", "list", "create", "update"]
{{- end -}}