apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonnet-translator
  labels:
    app: jsonnet-translator
spec:
  selector:
    matchLabels:
      app: jsonnet-translator
  replicas: 1
  template:
    metadata:
      labels:
        app: jsonnet-translator
    spec:
      serviceAccountName: sample-acc
      containers:
      - name: jsonnet-translator
        image: jsonnet-translator:latest
        imagePullPolicy: Never
        command: ["python","-u","sidecar/main.py"]
        args: [
          "--libsonnet",
          "https://github.com/bitnami-labs/kube-libsonnet@2c48e8e3fb40e38461ba27b05a290877c1e39cec",
          "https://github.com/thelastpickle/grafonnet-polystat-panel@275a48de57afdac0d72219d82863d8ab8bd0e682",
        ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-role
rules:
- apiGroups: ["*"]
  resources: ["configmaps", "prometheusrules"]
  verbs: ["get", "watch", "list", "create", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-acc
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample-rolebind
roleRef:
  kind: ClusterRole
  name: sample-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sample-acc
  namespace: default
